
export default new Map([
["src/content/principles/dry-principle.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprinciples%2Fdry-principle.mdx&astroContentModuleFlag=true")],
["src/content/principles/solid-principles.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprinciples%2Fsolid-principles.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/centralized-logging-and-monitoring.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Fcentralized-logging-and-monitoring.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/compound-components-pattern.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Fcompound-components-pattern.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/control-props-pattern.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Fcontrol-props-pattern.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/container-presentational.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Fcontainer-presentational.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/custom-hooks-for-abstraction.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Fcustom-hooks-for-abstraction.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/factory-hook-pattern.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Ffactory-hook-pattern.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/function-children-pattern.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Ffunction-children-pattern.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/graceful-degradation-fallback-uI.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Fgraceful-degradation-fallback-uI.mdx&astroContentModuleFlag=true")],
["src/content/patterns/observer-pattern.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpatterns%2Fobserver-pattern.mdx&astroContentModuleFlag=true")],
["src/content/patterns/singleton-pattern.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fpatterns%2Fsingleton-pattern.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/effect-synchronization.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Feffect-synchronization.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/error-boundaries.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Ferror-boundaries.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/higher-order-components.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Fhigher-order-components.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/provider-pattern.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Fprovider-pattern.mdx&astroContentModuleFlag=true")],
["src/content/react-patterns/render-props-pattern.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freact-patterns%2Frender-props-pattern.mdx&astroContentModuleFlag=true")]]);
		